### PR TITLE
feat: added homepage

### PR DESCRIPTION
**Pull request by hiteshverma27**

### CODE REVIEW

**Review by hrishikeshmane — APPROVED** [review]
Looks good to me.

**Review by ckahub — COMMENTED** [review]
LGTM

**Review by laxmikanthkonthum — COMMENTED** [review]
We are advised to avoid using inline styling. Also, there is no alt value for few images and rest looks good to me. Nicely done

**Comment by hiteshverma27** [comment]
> We are advised to avoid using inline styling. Also, there is no alt value for few images and rest looks good to me. Nicely done

It was for development and I was supposed to move it to style.css file but anyway thanks for pointing out

**Pull request merged**
